In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import wget

## Q1

In [3]:
pd.__version__

'2.2.2'

In [65]:
wget.download("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv")

'laptops (1).csv'

In [6]:
data = pd.read_csv("../data/laptops.csv")
data.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

## Q2

In [7]:
print(f"Total records: {data.shape[0]}")

Total records: 2160


## Q3

In [8]:
print(f"Total brands: {len(data["Brand"].unique())}")

Total brands: 27


## Q4

In [9]:
print(f"Columns with missing values: {len(list(filter(lambda x: len(x)==2, [data[column].isnull().unique() for column in data.columns])))}")

Columns with missing values: 3


## Q5

In [10]:
print(f"Max price of dell notebook: {data[data["Brand"] == "Dell"]["Final Price"].max()}")

Max price of dell notebook: 3936.0


## Q6

In [11]:
median_before = data["Screen"].median()
mode = data["Screen"].mode()
data[["Screen"]] = data[["Screen"]].fillna(mode)
median_after = data["Screen"].median()
print(f"Median before: {median_before} and median after: {median_after}")

Median before: 15.6 and median after: 15.6


## Q7

In [12]:
innjoo_laptops = data[data["Brand"] == "Innjoo"]
selected_columns = innjoo_laptops[["RAM", "Storage", "Screen"]]
X = selected_columns.values     # underlying numpy array
print(f"X shape: {X.shape}")

X shape: (6, 3)


In [13]:
# XTX
XTX = X.T@X
print(f"XTX:\n{XTX}")

XTX:
[[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]


In [14]:
# Inverse
XTX_inverse = np.linalg.inv(XTX)
print(f"Inverse XTX:\n{XTX_inverse}")

Inverse XTX:
[[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


In [15]:
## Proof 
identity_matrix = XTX@XTX_inverse
print(f"Approximetely identity matrix:\n{identity_matrix}")

Approximetely identity matrix:
[[ 1.00000000e+00 -9.35955990e-18  3.87908352e-15]
 [ 7.30229802e-14  1.00000000e+00  4.80687877e-14]
 [ 7.10542736e-15 -1.66533454e-16  1.00000000e+00]]


In [16]:
# Compute w 
y = np.array([1100, 1300, 800, 900, 1000, 1100])

w = (XTX_inverse @ X.T)@y
print(f"Result w:\n{w}")

Result w:
[45.58076606  0.42783519 45.29127938]


In [17]:
# Sum of the values
sum_w = w.sum()
print(f"Sum of w: {sum_w:.2f}")

Sum of w: 91.30
